@url = http://localhost:8080/api/departments
@token = eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJoZW5yeVdpbmN6bmVyIiwiaWF0IjoxNzM4NzI4NTAyLCJleHAiOjE3Mzk3Mjg1MDJ9.8TSWLJ99ccTVzvq2gVAbv4BGBW3-KiiwQo6TaMOyq0ttiKUnWTejR9heR2dqIthm0VHo_ZCyGNZQMKcmUtgB1Q

###GET all request
GET {{url}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

###GET by id request
GET http://localhost:8080/api/departments/1 HTTP/1.1

###POST request
POST {{url}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Software engineering",
  "description": "creating API endpoints with spring boot"
}

###
POST {{url}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Marketing",
  "description": "Manages stocks and stock holders"
}

###PUT request
PUT http://localhost:8080/api/departments/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "departmentId": "1",
    "name": "HR",
    "description": "Human resources"
}

###DELETE request
DELETE http://localhost:8080/api/departments/1 HTTP/1.1
Authorization: Bearer {{token}}