@token = eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJNYW5hZ2VyIiwiaWF0IjoxNzM4Nzg5ODc0LCJleHAiOjE3Mzk3ODk4NzR9.ozLF8nUKhlRYEpGrD8jUs7YtihDLSKVrxcgudCzw7tpEPcDlgKjgAQB3UfUNBLZkN_GaOJZ7AZPTTwIEy_lwPw 

### Get all leave requests
GET http://localhost:8080/api/leaves
Content-Type: application/json
Authorization: Bearer {{token}}

### Submit a new leave request
POST http://localhost:8080/api/leaves/submit?employeeId=1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "startDate": "2025-02-10",
  "endDate": "2025-02-15",
  "status": "PENDING",
  "reason": "Vacation",
  "managerComment": "Waiting for approval"
}



### Update a leave request status
PUT http://localhost:8080/api/leaves/update/2
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "status": "APPROVED"
}

### Delete a leave request
DELETE http://localhost:8080/api/leaves/1
Content-Type: application/json
Authorization: Bearer {{token}}
